# Generated by Django 4.2.13 on 2024-07-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_orders_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='mode',
            field=models.CharField(default='COD', max_length=20),
        ),
    ]
